import sbt._, Keys._

object MyBuild extends Build {
  val buildSettings = Defaults.defaultSettings ++ Seq(
    organization                := "ro.igstan",
    version                     := "0.1.0",
    scalaVersion                := "2.10.2",
    sourceDirectory in Compile <<= baseDirectory(_ / "src"),
    sourceDirectory in Test    <<= baseDirectory(_ / "test"),
    scalacOptions              ++= Seq(
      "-Ymacro-debug-lite", // Useful when debugging ASTs generated by macros.
      "-feature",
      "-deprecation",
      "-unchecked"
    )
  )

  lazy val macros = Project("macros",
    file("macros"),
    settings = buildSettings ++ Seq(
      libraryDependencies <+= (scalaVersion)("org.scala-lang" % "scala-compiler" % _)
    )
  )

  lazy val core = Project(
    "core",
    file("core"),
    settings = buildSettings
  ) dependsOn(macros)

  lazy val root = Project(
    "root",
    file("core"),
    settings = buildSettings
  ) aggregate(macros, core)
}
